name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run everything
      run: make new-all

    - name: Test
      run: make test

    - uses: actions/upload-artifact@v3
      with:
        name: release
        path: ./release
